name: Build csi-receiver firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    
    
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: esp32c5
            project: src/firmware-code/csi-receiver



    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build with ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5.3
          target: ${{ matrix.target }}
          path: ${{ matrix.project }}

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.target }}
          path: |
            ${{ matrix.project }}/build/*.bin
          if-no-files-found: warn
          retention-days: 7